const events = [
  {
    id: 1,
    name: "Lollapalooza", 
    description: "lorem ipsum...",
    image:
      "https://pbs.twimg.com/profile_images/1500933654830276608/PBf2KquH_400x400.jpg",
    date: "20-03-2022",
    hora: "17:00",
    location: "Hipódromo de Palermo, Buenos Aires",
    category: "Concierto",
    private: false,
    destacado: true,
    totalPrice: 11000,
  },
  {
    id: 2,
    name: "Cosquín Rock",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpE500YCm2dI6vMH2K6qMuPgMkDvJALf9RRg&usqp=CAU",
    date: "12-02-2022",
    hora: "15:00",
    location: "Aeroclub Santa María de Punilla, Córdoba",
    category: "Concierto",
    private: false,
    destacado: true,
    totalPrice: 9000,
  },
  {
    id: 3,
    name: "Quilmes Rock",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVjZhYW7SVyf8Akzzd-NNqmzXVEpJ6svC62Q&usqp=CAU",
    date: "30-04-2022",
    hora: "16:00",
    location: "Tecnópolis, Buenos Aires",
    category: "Concierto",
    private: false,
    destacado: true,
    totalPrice: 10500,
  },
  {
    id: 4,
    name: "Coldplay",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0Kt5VeujJ0DyJ2SXR956PDmi0sgAtcGKZhg&usqp=CAU",
    date: "25-10-2022",
    hora: "18:00",
    location: "Estadio River Plate, Buenos Aires",
    category: "Concierto",
    private: false,
    destacado: true,
    totalPrice: 15000,
  },
  {
    id: 5,
    name: "Cumpleaños Marcos",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEesccfOXtsDa18cKUjoB0aL8xtPr9-1gyWQ&usqp=CAU",
    date: "25-03-2022",
    hora: "21:00",
    location: "Antares Nueva Córdoba -  San Lorenzo 79, Córdoba",
    category: "Fiesta Privada",
    private: true,
    destacado: false,
  },
  {
    id: 6,
    name: "Cumpleaños Agustina",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0TgWEh39xjel0fQfshgcY3TrSyn21hsj_Xg&usqp=CAU",
    date: "26-03-2022",
    hora: "22:00",
    location: "Vidón-Bar - Achával Rodríguez 152, Córdoba",
    category: "Fiesta Privada",
    private: true,
    destacado: false,
  },
  {
    id: 7,
    name: "Cumpleaños Maggy",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREmFuC9yq-ZFwYGiyDNPXbjdyzB5gyNQHiGw&usqp=CAU",
    date: "25-03-2022",
    hora: "22:30",
    location:
      "Cruz Espacio -  Av. Ramón Cárcano 120, Chateau Carreras, Córdoba",
    category: "Fiesta Privada",
    private: true,
    destacado: false,
  },
  {
    id: 8,
    name: "Cumpleaños Gonzalo",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCy-dcspdIfjaL6dDUiRTP_LnFWGcA0kszMw&usqp=CAU",
    date: "28-03-2022",
    hora: "20:30",
    location: "Cervecería Capitán - Achával Rodríguez 244, Córdoba",
    category: "Fiesta Privada",
    private: true,
    destacado: false,
  },
  {
    id: 9,
    name: "After Office Globant",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxc21-gVXu_MP75NtGhUb1ZgOUBul90D2XRg&usqp=CAU",
    date: "28-03-2022",
    hora: "20:30",
    location: "Cervecería BarBeer - Hipólito Yrigoyen 81, Córdoba",
    category: "Evento Social",
    private: true,
    destacado: false,
  },
  {
    id: 10,
    name: "After Office Santex",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCy-dcspdIfjaL6dDUiRTP_LnFWGcA0kszMw&usqp=CAU",
    date: "30-03-2022",
    hora: "17:30",
    location: "Cervecería Capitán - Achával Rodríguez 244, Córdoba",
    category: "Evento Social",
    private: true,
    destacado: false,
  },
  {
    id: 11,
    name: "After Office Apex",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpeUvbserY2xOoPDrsGXRBZJ_sbQB4c6pWQQ&usqp=CAU",
    date: "31-03-2022",
    hora: "20:30",
    location: "Los Infernales - General Manuel Belgrano 631, Córdoba",
    category: "Evento Social",
    private: true,
    destacado: false,
  },
  {
    id: 12,
    name: "Futbol 7 - Juan",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPL4Q6vuNOp5wxqkn2QqFv1xhStEKW9__cpw&usqp=CAU",
    date: "25-03-2022",
    hora: "21:00",
    location: "La Gran 7 -  Concepción Arenal, Córdoba",
    category: "Deportes",
    private: true,
    destacado: false,
  },
  {
    id: 13,
    name: "Futbol 7 - Marcos",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPL4Q6vuNOp5wxqkn2QqFv1xhStEKW9__cpw&usqp=CAU",
    date: "25-03-2022",
    hora: "20:00",
    location: "La Gran 7 -  Concepción Arenal, Córdoba",
    category: "Deportes",
    private: true,
    destacado: false,
  },
  {
    id: 14,
    name: "Futbol 7 - Micaela",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPL4Q6vuNOp5wxqkn2QqFv1xhStEKW9__cpw&usqp=CAU",
    date: "26-03-2022",
    hora: "21:00",
    location: "La Gran 7 -  Concepción Arenal, Córdoba",
    category: "Deportes",
    private: true,
    destacado: false,
  },
  {
    id: 15,
    name: "Futbol 7 - Pedro",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPL4Q6vuNOp5wxqkn2QqFv1xhStEKW9__cpw&usqp=CAU",
    date: "26-03-2022",
    hora: "20:00",
    location: "La Gran 7 -  Concepción Arenal, Córdoba",
    category: "Deportes",
    private: true,
    destacado: false,
  },
  {
    id: 16,
    name: "Lista Flor ",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyP3Hr_QSJrNZhIxvJnxi98mD4SFnUyoUD8sPiGEAWYTdHV4JIRIG9q5Y8Z8zWaxugiSE&usqp=CAU",
    date: "26-03-2022",
    hora: "22:00",
    location: "Le Parc -  Av Vélez Sarsfield 753, Córdoba",
    category: "Bar Experience",
    private: true,
    destacado: false,
  },
  {
    id: 17,
    name: "Lista Agus",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyP3Hr_QSJrNZhIxvJnxi98mD4SFnUyoUD8sPiGEAWYTdHV4JIRIG9q5Y8Z8zWaxugiSE&usqp=CAU",
    date: "26-03-2022",
    hora: "22:00",
    location: "Bartó -   Av. Marcelo T. de Alvear 635, Córdoba",
    category: "Bar Experience",
    private: true,
    destacado: false,
  },
  {
    id: 18,
    name: "Lista Cande",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyP3Hr_QSJrNZhIxvJnxi98mD4SFnUyoUD8sPiGEAWYTdHV4JIRIG9q5Y8Z8zWaxugiSE&usqp=CAU",
    date: "26-03-2022",
    hora: "20:00",
    location: "María María -  Av. Marcelo T. de Alvear 386, Córdoba",
    category: "Bar Experience",
    private: true,
    destacado: false,
  },
  {
    id: 19,
    name: "Spydi y sus amigos",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIWCNfj4tROoI0ZQRLa_dpI-_76pvNY-o5cQ&usqp=CAU",
    date: "30-03-2022",
    hora: "22:15",
    location: "Hoyts Patio Olmos, Córdoba",
    category: "Cine",
    private: false,
    destacado: true,
    totalPrice: 900,
  },
  {
    id: 20,
    name: "Batman",
    description: "lorem ipsum...",
    image:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.rNWoTqiGrlXCznxK5vnRpwHaEK%26pid%3DApi&f=1",
    date: "01-04-2022",
    hora: "23:25",
    location: "Hoyts Nuevo Centro, Córdoba",
    category: "Cine",
    private: false,
    destacado: true,
    totalPrice: 900,
  },
  {
    id: 21,
    name: "Spiderman",
    description: "lorem ipsum...",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIWCNfj4tROoI0ZQRLa_dpI-_76pvNY-o5cQ&usqp=CAU",
    date: "01-04-2022",
    hora: "23:00",
    location: "Hoyts Nuevo Centro, Córdoba",
    category: "Cine",
    private: false,
    totalPrice: 800,
  },
  {
    id: 22,
    name: "Kolombo",
    description: "lorem ipsum...",
    image: "https://virtualtkt.com/repo/images/VAG4X9.jpg",
    date: "01-05-2022",
    hora: "23:25",
    location: "Visión Festival - Neuquén",
    category: "Fiesta",
    private: false,
    totalPrice: 6000,
    destacado: true,
  },
  {
    id: 23,
    name: "Hernán Cattáneo",
    description: "lorem ipsum...",
    image:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/536/860/products/libro-hernan-cattaneo1-4d6d150966d1dce0fa16230298728167-480-0.jpg",
    date: "01-04-2022",
    hora: "00:00",
    location: "Río Electronic Music - Buenos Aires",
    category: "Fiesta",
    private: false,
    totalPrice: 4500,
    destacado: true,
  },
  {
    id: 24,
    name: "Feria degustar",
    description: "lorem ipsum...",
    image:
      "https://www.infobae.com/new-resizer/wd2nNWDrR-JsJvAgXNGQtbZeOvs=/1200x900/filters:format(webp):quality(85)//s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2019/05/20114815/vinos-41.jpg",
    date: "01-04-2022",
    hora: "23:25",
    location: "Palermo - Buenos Aires",
    category: "Gastronomía",
    private: false,
    totalPrice: 2100,
  },
  {
    id: 25,
    name: "Maldini Fest",
    description: "lorem ipsum...",
    image:
      "https://www.saavedraonline.com.ar/wp-content/uploads/2020/03/maldini.jpg",
    date: "01-04-2022",
    hora: "23:25",
    location: "Saavedra - Buenos Aires",
    category: "Fiesta",
    private: false,
    totalPrice: 6000,
  },
  {
    id: 26,
    name: "Pltz",
    description: "lorem ipsum...",
    image:
      "https://i0.wp.com/revistag7.com/wp-content/uploads/2021/02/MG_6734_edicion_alta.jpg?fit=1080%2C720&ssl=1",
    date: "01-04-2022",
    hora: "23:25",
    location: "Palermo - Buenos Aires",
    category: "Bar",
    private: false,
    totalPrice: 3000,
  },
  {
    id: 27,
    name: "Teatro Ciego",
    description: "lorem ipsum...",
    image:
      "https://encolombia.com/wp-content/uploads/2021/07/Elementos-del-Teatro.jpg",
    date: "03-06-2022",
    hora: "20:20",
    location: "Recoleta - Buenos Aires",
    category: "Teatro",
    private: false,
    totalPrice: 1400,
  },
  {
    id: 28,
    name: "A ciegas Gourmet",
    description: "lorem ipsum...",
    image:
      "https://offloadmedia.feverup.com/madridsecreto.co/wp-content/uploads/2021/03/03044328/dining-in-the-dark-madrid-3.jpg",
    date: "29-03-2022",
    hora: "20:25",
    location: "Recoleta - Buenos Aires",
    category: "Restaurant",
    private: false,
    totalPrice: 600,
    destacado: true,
  },
  {
    id: 29,
    name: "The Hobbit",
    description: "lorem ipsum...",
    image: "https://wallpaperaccess.com/full/830842.jpg",
    date: "20-04-2022",
    hora: "22:00",
    location: "Cinemark Palermo - Buenos Aires",
    category: "Cine",
    private: false,
    totalPrice: 1000,
    destacado: true,
  },
  {
    id: 30,
    name: "Dune",
    description: "lorem ipsum...",
    image:
      "https://lh3.googleusercontent.com/-km726JvA5ds/YTlfBh2p8dI/AAAAAAAAOCo/3iyoTQtCoBArMzkOP2Q9tDgmfAneRwZJgCLcBGAsYHQ/w437-h640/E-xdddtWQAQ3YLh.jpg",
    date: {
      startDate: "14-5-2021"
    },
    hora: "21:00",
    location: "IMAX - Buenos Aires",
    category: "Cine",
    private: false,
    totalPrice: 900,
  },
];

module.exports = events;
